### ISSUE TITLE
systemd-udevd takes high CPU on CoreOS stable v835.9.0

### ISSUE THREAD

**Issue by ntquyen** [paulshir/coreos-hyperv#11]
Hi @paulshir, I'm not sure if this is the right place to post this issue, but since I use your nice script to create CoreOS in Hyper-V, I thought it would be easier for you to reproduce it, since it seems that there is only me who got this issue.

This is the duplicate of the issue: https://github.com/coreos/bugs/issues/1036. I hope you would take a look at it when you have time, thanks!

**Comment by paulshir** [comment]
Hey @ntquyen,
My script is really just a wrapper using to download and setup coreos hyperv images. The issue you are having is with coreos itself. The other bug you opened will help you a lot more then I can.
