### ISSUE TITLE
Can the script support vhdx for main hard drive?

### ISSUE THREAD

**Issue by ntquyen** [paulshir/coreos-hyperv#13]
I think it would be better to have .vhdx for the main hard drive. I don't know but is there any trouble to support that? Or is there any options to go with vhdx?

**Comment by paulshir** [comment]
Hi,

It would be possible to support that but it is something that I won't be able to take on at the moment and don't really see much benefit. If you are really interested in doing this you could look [here](https://blogs.msdn.microsoft.com/virtual_pc_guy/2012/10/03/using-powershell-to-convert-a-vhd-to-a-vhdx/)

How the script works is that it downloads the compressed imaged VHD from the coreos website. The script then decompresses it and makes a copy for every instance requested. It then expands the size of the VHD for each instance to make it more useable. The script then creates VHDX drives with the cloud-configs and attaches them to the instance also.

To convert to VHDX would require either to get a VHDX from coreos, or convert the VHD from coreos to VHDX.

**Comment by ntquyen** [comment]
Thanks @paulshir!
