### ISSUE TITLE
msys bunzip2 instead of gnuwin bunzip2

### ISSUE THREAD

**Issue by so0k** [paulshir/coreos-hyperv#5]
Small suggestion, maybe this could be useful:

If msys git is installed, there is no need to download gnuwin bunzip2. 

This works:
`& "${env:ProgramFiles(x86)}\Git\bin\sh.exe" -login bunzip2 -d -k $config2_basebz2 2>&1`

Also, thank you for this repo, I was using `mkisofs` from this link:
http://www.student.tugraz.at/thomas.plank/index_en.html

but that didn't work anymore, thanks to your repo, I no longer depend on mkisofs and can just use a VHD config-drive.

now I also want to eliminate the need for gnuwin as msysgit is minimum required.

**Comment by so0k** [comment]
is it possible to create the config2_base.vhdx with the NEW-VHD commandlet? or is there an issue formatting the disk (assigning volume label and such) - how did you create that vhdx? (mount into a Linux machine and mkfs?)

**Comment by so0k** [comment]
ah, I noticed you used to use
`$vhd = New-VHD -Path $drvhdlocation -Dynamic -SizeBytes 100MB | Mount-VHD -Passthru | Initialize-Disk -PartitionStyle MBR -PassThru | New-Partition -AssignDriveLetter:$false -UseMaximumSize | Format-Volume -FileSystem FAT -Confirm:$false -Force | Get-Partition | Add-PartitionAccessPath -AssignDriveLetter -PassThru | Get-Volume`

**Comment by so0k** [comment]
Not sure how to format the New-VHD, so I'm using the following commands (for now):

    iwr -Uri "https://github.com/paulshir/coreos-hyperv/raw/master/files/config2_base.vhdx.bz2" -OutFile "config2_base.vhdx.bz2"
    & "${env:ProgramFiles(x86)}\Git\bin\sh.exe" -login bunzip2 -c -k $config2_basebz2 > config2_base.vhdx 2>&1

**Comment by paulshir** [comment]
Hey.

I'm away on holidays without a computer so won't be able to do much for 2 weeks.

I like the idea of mysgit. Will implement that when I'm back.

In regards to the configuration vhd. I created it on a Linux cm by mounting a vhd file and using mkfs. I can send the exact instructions. I would much prefer if I could create the vhd each time but when I create the vhd in Windows the label is in all caps (CONFIG_2 I think). Coreos doesn't recognise the uppercase and requires it to be lowercase. To get around this I created the configuration base in Linux and just copy it instead.

**Comment by paulshir** [comment]
I've add this support now.

https://github.com/paulshir/coreos-hyperv/pull/7

**Comment by so0k** [comment]
wow, so much nicer! 

```powershell
$msysgit = Split-Path (get-command git).Definition -Parent | Split-Path -Parent
$bzip = Join-Path $msysgit "bin\bzip2.exe"
& cmd /C "`"`"$Bzip`" -c -d -k `"$Target`" > `"$Destination`"`"" | Out-Null
```

sweet stuff, I was struggling calling bunzip through sh.exe as I thought it required to be called that way
