### ISSUE TITLE
Windows native docker client

### ISSUE THREAD

**Issue by so0k** [paulshir/coreos-hyperv#6]
Not sure if this possible/relevant to your cluster setup, I'm still playing with a single CoreOS VM.
But... Since docker version 1.6.0, windows client is stable. Would it be useful to integrate the docker client setup as part of the powershell script as well? This involves 2 steps:

1. Set up Docker socket on CoreOS
https://coreos.com/docs/launching-containers/building/customizing-docker/#cloud-config

2. Download Docker windows binaries set path, docker_host, ...: 
https://docs.docker.com/installation/binaries/#get-the-windows-binary

```powershell
    iwr https://get.docker.com/builds/Windows/x86_64/docker-latest.exe -Outfile docker.exe
```

**Comment by paulshir** [comment]
I'm use this script to spin up and down many clusters so I don't really want to download the docker binaries automatically as that is more of a one off thing. I also don't want to presume where people like to install things etc. 

I will update my sample config with one that can connect to docker over the docker socket. I have created this before but never got around to testing it.

**Comment by paulshir** [comment]
I've updated the sample config now. You can now connect to docker remotely using `docker -H tcp://<vm_ip>:2375 <cmd>`

**Comment by so0k** [comment]
thanks!
